jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'db_dev'
      schema: 'main'
      schemas_and_paths:
        main: 'dev.db'
      schema_directory: './'
    prod:
      type: sqlite
      threads: 1
      database: 'db_prod'
      schema: 'main'
      schemas_and_paths:
        main: 'prod.db'
      schema_directory: './'

